# Site settings
title: Great New Blog Title
author:
  name: Martin Souchier
  email: souchier@stanford.edu
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
